### ISSUE TITLE
Clarification on how the markTokenset feature works

### ISSUE THREAD

**Issue by mihkeleidast** [divriots/style-dictionary-to-figma#15]
In the README, it says that:

> Allows marking a category as a custom tokenset so that it will appear as a separate tokenset in Figma. This is useful if you want to combine many base tokens into a "global" set for example.

This is exactly what I want to do. However, it seems like Figma Tokens might not support this anymore? E,g, in Figma Tokens, it seems that every tokenset is a separate JSON, and `markTokenset ` in the same JSON does not have any effect.

I might be doing something wrong, so looking for clarification whether this is supposed to work or not. Thanks!

**Comment by jorenbroekema** [comment]
Hey, thanks for bringing this to my attention. 

It seems as though the tokenset meta information since the last update is now stored in the Figma Tokens plugin itself, so there's no way to create a JSON file from the outside as input to the plugin that populates the tokens in separate tokensets.

I'll ask Jan if he can advise, maybe there's a way still to do this or perhaps he'd consider a meta prop in his JSON format for us to allow doing this again.

**Comment by mihkeleidast** [comment]
Yeah, the alternative I've thought about would be to export separate JSON files from style-dictionary through filtering, but it would simplify setting up sync if there were less JSON files.

**Comment by jorenbroekema** [comment]
I'm not sure if you can specify multiple JSON files in the plugin as input source?
![image](https://user-images.githubusercontent.com/36734656/168570332-24059259-d38d-4c8b-b3da-b4807f7fa6a8.png)

Seems to imply it's just 1 JSON file path.

**Comment by jorenbroekema** [comment]
What you could do is export it like you're doing, you get it all in 1 token set, and then you can create the other tokensets that you need and just Cut & Paste the JSON pieces in plugin. It's a bit of manual work of course, not sure how many sets you've got or how big your JSON is.

**Comment by mihkeleidast** [comment]
Interesting, I haven't actually set up the sync yet - thought that it is possible to specify that for each tokenset, but it does seem to be global. I wonder how it's set up in the reverse direction (i.e. syncing from figma to github), how does is store the tokens then? Might be that the tokenset feature only supports exteranl sync and not manually importing the JSON, which, while a bit weird, would eventually work for me as well.

**Comment by jorenbroekema** [comment]
It seems I misunderstood. There's no regression from the Figma Tokens Plugin, I was reading the JSON from my own project but I forgot I ran the token-transformer over it and transform to style-dictionary format (so basically doing the reverse of what style-dictionary-to-figma does), so the tokensets info is removed there. My bad!

The way this is supposed to work is as follows,

You start with style-dictionary JSON, for example:
```json
{
  "colors": {
    "tokenset": "set-core",
    "accent": {
      "base": {
        "type": "color",
        "value": "#F8C307"
      },
      "bright": {
        "type": "color",
        "value": "#FFD63B"
      }
    }
  }
}
```

This will be processed by `style-dictionary-to-figma` to give you the following output (roughly speaking, there will be more metadata as well):

```json
{
  "set-core": {
    "colors": {
      "accent": {
        "base": {
          "type": "color",
          "value": "#F8C307"
        },
        "bright": {
          "type": "color",
          "value": "#FFD63B"
        }
      }
    }
  }
}
```

This JSON is the interpreted by the Figma Tokens Plugin, it takes the uppermost property in the JSON as the tokenset, and then what is nested inside will be displayed under that tokenset in the plugin "JSON" tab like so:
```json
{
  "colors": {
    "accent": {
      "base": {
        "type": "color",
        "value": "#F8C307"
      },
      "bright": {
        "type": "color",
        "value": "#FFD63B"
      }
    }
  }
}
```

**Comment by mihkeleidast** [comment]
This works only via the sync feature, right? I.e. it is not possible to paste that second JSON (the output of style-dictionary-to-figma w/ tokensets) to Figma Tokens manually, as that manual JSON editing expects the third format already?

**Comment by jorenbroekema** [comment]
Yeah I'll add a blockquote note about needing to use the FT sync feature for this.

Perhaps it could be an idea to add a flag to the transformer that outputs every tokenset in a separate JSON file (the third snippet, multiple), so you can copy paste into the tokensets JSON in the plugin? Would that be useful to you? I'd still recommend using the sync feature though but I'd be happy to add this flag if it adds value to you right now.

**Comment by mihkeleidast** [comment]
This could be useful, but no need to implement anything for me yet. Not sure this can be done in this transformer, as it doesn't deal with writing files at all currently, that is handled by SD? I might be able to do this on my own by running this formatter multiple times with different filters. Planning to get the sync up and running as well soon, so this need would be too temporary to spend too much time on it :)
