### ISSUE TITLE
Allow useRefValue on some tokens, but not on others

### ISSUE THREAD

**Issue by mihkeleidast** [divriots/style-dictionary-to-figma#17]
I'm trying to work around this Figma Tokens issue: https://github.com/six7/figma-tokens/issues/706

Our shadow tokens are defined as follows:
```json
{
  "shadow": {
    "core": {
      "2": {
        "value": {
          "x": "0",
          "y": "1",
          "blur": "2",
          "spread": "0",
          "color": "{color.core.black.8}",
          "type": "dropShadow"
        }
      },
      "4": {
        "value": {
          "x": "0",
          "y": "2",
          "blur": "4",
          "spread": "0",
          "color": "{color.core.black.8}",
          "type": "dropShadow"
        }
      },
      "8": {
        "value": {
          "x": "0",
          "y": "4",
          "blur": "8",
          "spread": "0",
          "color": "{color.core.black.8}",
          "type": "dropShadow"
        }
      }
    },
    "elevation": {
      "small": {
        "value": ["{shadow.core.4}", "{shadow.core.2}"]
      },
      "medium": {
        "value": ["{shadow.core.8}", "{shadow.core.2}"]
      }
    }
  }
}
```
Our elevation shadows stack the different core shadows and we'd like to not have to duplicate those definitions. We would like to  use `useRefValue`, so the token relationships would be visible in Figma Tokens as well. This is impossible currently due to how our tokens are defined and the FT issue I linked above.

Is there an easy way of adding some sort of filtering to `useRefValue`, so that the specific `shadow.elevation.small.value` would not use references, but everything else still would?

**Comment by jorenbroekema** [comment]
I see, yeah I guess we can make a little something to work around that problem, I propose a boolean metadata flag that you can put in your token (as a sibling to the value prop) to flag it was "ignore this one for useRefValue function".

https://github.com/divriots/style-dictionary-to-figma/pull/18

I think that should allow you to work around the problem then?

Let me know!

**Comment by mihkeleidast** [comment]
Ooh that seems nice! This is definitely a better workaround than not using references at all, but it does lose the internal color reference currently. If this is more difficult to solve, I understand, does not matter too much.
