### ISSUE TITLE
Tailwind CSS → Style Dictionary → Figma Tokens

### ISSUE THREAD

**Issue by ajmalafif** [divriots/style-dictionary-to-figma#28]
Thank you for this, @divriots. Seeing that green ✔ in the terminal feels good (as a designer) 🙇‍♂️

**Intention**
So my setup was I wanted to pull tailwindcss default --full config into Design Tokens so for anything that is vanilla/default tailwind, I can apply them in my design. For example, I want to apply an equivalent of `space-x-4` or `gap-4` via Figma Tokens (which is `1rem`) on my Figma, so it's consistent with tailwindcss when developers use that specific class.

However, after transforming from SD to `JSON` I noticed some tokens were not “categorized” in the format that Figma Tokens utilize. I am sure this isn‘t a bug of `style-dictionary-to-figma` but more a specific transformer code I need to figure out to fix this:
<img width="547" alt="CleanShot 2022-09-13 at 22 58 22@2x" src="https://user-images.githubusercontent.com/827167/189938014-de1180e9-dd80-4490-b37e-0b52ab5891d5.png">

I would appreciate any pointers that can help me find progress in the right direction. I understand if this is out of scope, but I want to thank you again for making a designer like myself feel this is solvable. Here‘s what I got so far: https://github.com/ajmalafif/tailwind-to-style-dictionary/blob/sd-to-figma/style-dictionary.config.js

**Comment by jorenbroekema** [comment]
Hey! If the tokens end up uncategorized in figma tokens plugin, it means those tokens don't have a type attribute that matches any of the plugins category names. You can adjust or add the types in the tokens source of truth (I am assuming style dictionary) to match the figma plugin categories accordingly, then they'll show up correctly.

**Comment by ajmalafif** [comment]
I see! thank you, @jorenbroekema, and also all the videos you made. I went over almost all your videos for Backlight!

Yes, I‘m using style dictionary. Okay, I think this definitely validates where I am going in the right path/direction, so I‘ll figure it out **how** do I adjust or add the types?

**Comment by jorenbroekema** [comment]
Glad they were helpful!

```json
{
  "color": {
    "primary": {
      "type": "color",
      "value": "ff0000"
    }
  }
}
```

So either adjust the type property or add one if it's not there yet. Figma tokens plugin should have some docs on the types they use for their categories.
